/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BrigadaData;
import AccesoADatos.CuartelData;
import Entidades.Brigada;
import Entidades.Cuartel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class BrigadasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BrigadasView
     */
    public BrigadasView() {
        initComponents();
        LlenarCBCuarteles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNombreBrigada = new javax.swing.JTextField();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jcEspecialidad = new javax.swing.JComboBox<>();
        jtEstado = new javax.swing.JTextField();
        jtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbBajas = new javax.swing.JButton();
        jbAltas = new javax.swing.JButton();
        jbLimpiarCampos = new javax.swing.JButton();
        jcCuartel = new javax.swing.JComboBox<>();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("BRIGADAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 111, 38));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre brigada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 155, -1, 27));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Especialidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 200, 112, 22));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Cuartel");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 300, 100, 24));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Estado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 251, 112, 24));
        jPanel1.add(jtNombreBrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 160, 296, -1));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 388, 107, -1));

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 388, 107, -1));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 108, 92, -1));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 388, 107, -1));

        jcEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione especialidad", "Incendios en viviendas e industrias", "Salvamento en derrumbes", "Rescates en ámbito montaña", "Rescate de personas atrapadas en accidentes de tráfico", "Socorrer inundaciones", "Operativos de prevención" }));
        jPanel1.add(jcEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 203, -1, -1));

        jtEstado.setEditable(false);
        jPanel1.add(jtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 251, 171, -1));
        jPanel1.add(jtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 109, 191, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID de brigadas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 109, -1, -1));

        jbBajas.setText("Dar de Baja");
        jbBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajasActionPerformed(evt);
            }
        });
        jPanel1.add(jbBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 388, 107, -1));

        jbAltas.setText("Dar de Alta");
        jbAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltasActionPerformed(evt);
            }
        });
        jPanel1.add(jbAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 388, 107, -1));

        jbLimpiarCampos.setText("Limpiar Campos");
        jbLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(jbLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, 20));

        jPanel1.add(jcCuartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 304, 296, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarCamposActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jbLimpiarCamposActionPerformed

    private void jbAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltasActionPerformed
        // TODO add your handling code here:
        BrigadaData brd = new BrigadaData();
 
        brd.darDeAlta(Integer.parseInt(jtId.getText()));

        limpiarCampos();

    }//GEN-LAST:event_jbAltasActionPerformed

    private void jbBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajasActionPerformed
        // TODO add your handling code here:
        BrigadaData brd = new BrigadaData();
        Brigada b = new Brigada();

        brd.darDeBaja(Integer.parseInt(jtId.getText()));

        limpiarCampos();

    }//GEN-LAST:event_jbBajasActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jtId.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Complete el campo ID correctamente");
        } else {
            BrigadaData brd = new BrigadaData();
            Brigada bb = new Brigada();
            CuartelData cd = new CuartelData();
            bb = brd.buscarBrigada(Integer.parseInt(jtId.getText()));
            //  limpiarCampos();
            if (bb.getNombre() != null) {

                jtNombreBrigada.setText(bb.getNombre());
                jtId.setText(bb.getCodigo() + "");
                if (bb.isEstado()==true) {
                    jtEstado.setText("Activo");
                } else {
                    jtEstado.setText("Inactivo");
                }
                jcEspecialidad.setSelectedItem(bb.getEspecialidad());

                jcCuartel.setSelectedItem(bb.getCuartel().toString());

            }
        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
if (jtNombreBrigada.getText().length() > 0 && jcEspecialidad.getSelectedIndex() != 0 && jcCuartel.getSelectedIndex() != 0) {
        BrigadaData brd = new BrigadaData();
        Brigada b = new Brigada();
        b.setNombre(jtNombreBrigada.getText());
        b.setEspecialidad((String) jcEspecialidad.getSelectedItem());
        b.setEstado(true);
        b.setLibre(true);
        CuartelData cd = new CuartelData();
        ArrayList<Cuartel> cuarteles = cd.listarCuartel();
    
        b.setCuartel(cuarteles.get(jcCuartel.getSelectedIndex()-1));
        
        Brigada br = (Brigada)brd.buscarBrigada(Integer.parseInt(jtId.getText()));
        b.setCodigo(br.getCodigo());
        
        brd.modificarBrigada(b);

        limpiarCampos();
}else{
JOptionPane.showMessageDialog(null, "Complete todos los campos");
}
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed

        BrigadaData brd = new BrigadaData();
        Brigada b = new Brigada();
        if (jtNombreBrigada.getText().length() > 0 && jcEspecialidad.getSelectedIndex() != 0 && jcCuartel.getSelectedIndex() != 0) {
            b.setNombre(jtNombreBrigada.getText());
            b.setEspecialidad((String) jcEspecialidad.getSelectedItem());
            b.setEstado(true);
            b.setLibre(true);
            CuartelData cd = new CuartelData();
            ArrayList<Cuartel> cuarteles = cd.listarCuartel();
            
            
            b.setCuartel(cuarteles.get(jcCuartel.getSelectedIndex()-1));

            brd.guardarBrigada(b);

            limpiarCampos();
        }else{
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }
       
     

    }//GEN-LAST:event_jbAgregarActionPerformed
    private void LlenarCBCuarteles() {
        Cuartel c = new Cuartel();
        ArrayList<Cuartel> cuarteles = new ArrayList<>();
        CuartelData cd = new CuartelData();
        cuarteles = cd.listarCuartel();
//        Cuartel cl = new Cuartel("Seleccione el Cuartel");
//        if (j != 1) {
//            jcCuartel.addItem(cl);
//        }
        jcCuartel.addItem("Seleccione el Cuartel");
        for (Cuartel cuartel : cuarteles) {
            jcCuartel.addItem(cuartel.toString());
        }
    }

    private void limpiarCampos() {

        jtNombreBrigada.setText("");
        jtEstado.setText("");
        jcCuartel.setSelectedIndex(0);
        jcEspecialidad.setSelectedIndex(0);
        jtId.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbAltas;
    private javax.swing.JButton jbBajas;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbLimpiarCampos;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcCuartel;
    private javax.swing.JComboBox<String> jcEspecialidad;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombreBrigada;
    // End of variables declaration//GEN-END:variables
}
