/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Juan
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmBombero = new javax.swing.JMenu();
        jmFormularioBombero = new javax.swing.JMenuItem();
        jBrigadas = new javax.swing.JMenu();
        jmFormularioBrigadas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmFormularioCuarteles = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmFormularioSiniestro = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        Escritorio.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jmBombero.setBackground(new java.awt.Color(255, 255, 255));
        jmBombero.setForeground(new java.awt.Color(0, 0, 0));
        jmBombero.setText("Bomberos");

        jmFormularioBombero.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioBombero.setForeground(new java.awt.Color(0, 0, 0));
        jmFormularioBombero.setText("Formulario Bombero");
        jmFormularioBombero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioBomberoActionPerformed(evt);
            }
        });
        jmBombero.add(jmFormularioBombero);

        jMenuBar1.add(jmBombero);

        jBrigadas.setBackground(new java.awt.Color(255, 255, 255));
        jBrigadas.setForeground(new java.awt.Color(0, 51, 51));
        jBrigadas.setText("Brigadas");

        jmFormularioBrigadas.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioBrigadas.setForeground(new java.awt.Color(0, 0, 0));
        jmFormularioBrigadas.setText("Formulario Brigadas");
        jmFormularioBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioBrigadasActionPerformed(evt);
            }
        });
        jBrigadas.add(jmFormularioBrigadas);

        jMenuBar1.add(jBrigadas);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setText("Cuarteles");

        jmFormularioCuarteles.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioCuarteles.setForeground(new java.awt.Color(0, 0, 0));
        jmFormularioCuarteles.setText("Formulario Cuarteles");
        jmFormularioCuarteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioCuartelesActionPerformed(evt);
            }
        });
        jMenu3.add(jmFormularioCuarteles);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setText("Siniestros");

        jmFormularioSiniestro.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioSiniestro.setForeground(new java.awt.Color(0, 0, 0));
        jmFormularioSiniestro.setText("Formulario Siniestro");
        jmFormularioSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioSiniestroActionPerformed(evt);
            }
        });
        jMenu4.add(jmFormularioSiniestro);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFormularioBomberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioBomberoActionPerformed
        
        Escritorio.removeAll();
        Escritorio.repaint();
        BomberoView bv = new BomberoView();
        bv.setVisible(true);
        Escritorio.add(bv);
        Escritorio.moveToFront(bv);

        
    }//GEN-LAST:event_jmFormularioBomberoActionPerformed

    private void jmFormularioCuartelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioCuartelesActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        CuartelView cv = new CuartelView();
        cv.setVisible(true);
        Escritorio.add(cv);
        Escritorio.moveToFront(cv);

    }//GEN-LAST:event_jmFormularioCuartelesActionPerformed

    private void jmFormularioBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioBrigadasActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        BrigadasView brv = new BrigadasView();
        brv.setVisible(true);
        Escritorio.add(brv);
        Escritorio.moveToFront(brv);
    }//GEN-LAST:event_jmFormularioBrigadasActionPerformed

    private void jmFormularioSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioSiniestroActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        SiniestroView sv = new SiniestroView();
        sv.setVisible(true);
        Escritorio.add(sv);
        Escritorio.moveToFront(sv);
    }//GEN-LAST:event_jmFormularioSiniestroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jBrigadas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmBombero;
    private javax.swing.JMenuItem jmFormularioBombero;
    private javax.swing.JMenuItem jmFormularioBrigadas;
    private javax.swing.JMenuItem jmFormularioCuarteles;
    private javax.swing.JMenuItem jmFormularioSiniestro;
    // End of variables declaration//GEN-END:variables
}
